version: "3.8"
services: 
    scrapy:
        container_name: scrapy
        # build: .
        image: nitaydockerhub/scrapy:0.4
        volumes: 
            - ./:/app/
        working_dir: /app/customproxy
        command: ["scrapy","crawl","cproxy"]
